### PR TITLE
Guarded Implementation of trying to get Citadel info from ESI if Hammer API does not know it.

### PR DESCRIPTION
**Pull request by SpeedProg**
Next try to improve this.
I added a preprocessor guarded implementation of falling back to ESI if the Hammer API does not know a citadel.
Citadel Hunt API doesn't know the citadels I use and I don't really want them on there either.

Would be nice if this can be review and commented on.

### CODE REVIEW

**Comment by SpeedProg** [comment]
There seems to be a race condition where sometimes CharacterIndustryJobsList.EveMonClient_ConquerableStationListUpdated is not registered as callback yet when the citadel info is already loaded.
Maybe IndustryJob should have it's own callback :/ not too sure about this.

**Comment by peterhaneve** [comment]
I like this idea but have some minor issues:

- You are right in stating that a given citadel request would need to be associated with a calling character. However, I would compute `FindAPIKeyWithAccess` when the request is queued.
- Likewise, parallel data structures make the code harder to understand and invite future bugs. Instead, I would probably parameterize the `GenericIDToNameProvider` and allow the tagged information to be stored in the queue (changing the `Set` to a `Dictionary`.
- Perhaps having ESI as primary with a hammertime fallback would be good. If a character gets assets marooned in a locked out citadel EVEMon would stand a fighting chance at identifying it.

**Comment by SpeedProg** [comment]
So i did the changes you suggested (also removed the preprocessor guards, if you really want it optional I can just add them when it if finished).

But if we do it this way round (esi to hammertime as fallback) I think I am going to need to keep track of the esi error header somehow, since after 100 errors per minute you get blocked (until the minute is over).
If that happens I'd try to resolve them with hammer time first and if hammertime does not know them put them in a "esi-only" queue where it tries to resolve them once the error limit got freed.

**Comment by peterhaneve** [comment]
Nothing against your PR, but I am going to be busy for the next two weeks and may not have time to look at this in detail.

**Comment by SpeedProg** [comment]
So yeah I merged the current master into this and fixed the Installation not getting updated sometimes by adding an other UpdateInstallation that gets called after callback handers are registered by the CharacterIndustryJobsList. (just how UpdateLocation is called there too)

**Comment by peterhaneve** [comment]
The main issue with preferring hammer time is that hammer time can easily get out of date. While this (if the data was accurate originally) only matters if the citadel gets renamed (not a big deal) or blown up, it is still something to consider.

Where is the 100 error per minute item mentioned? I may want to track this for, say, ID->Name lookups across the application as a whole.

**Comment by SpeedProg** [comment]
So if an esi request throws an error (4xx or 5xx) you get a error counted against your limit and you have a moving? window of 60s and 100 errors. 
More info
https://developers.eveonline.com/blog/article/error-limiting-imminent
https://developers.eveonline.com/blog/article/esi-error-limits-go-live

**Comment by peterhaneve** [comment]
Interesting. Since EVEMon currently uses one app key per user (yeah I don't like it but without PKCE the other way requires me to run a web server that I don't want to maintain) hitting 100 errors in a minute would be an achievement, but definitely something to look at if EVEMon finds a way to use a shared key.

**Comment by SpeedProg** [comment]
No, no you misunderstood me. The limit is global over the endpoints per ip/appid. So if you have a different ip but same appid you have a different error count as far as I know :).
Okay so I guess that means you are okay with me not implementing error count tracking on the citadel lookups? If so this pull request is at a state it can be merged at.

**Comment by peterhaneve** [comment]
It looks like there is a header, `X-ESI-Error-Limit-Remain`, which we can trap on if it is under a threshold and back off future queries (which might error) until the window expires?

**Comment by SpeedProg** [comment]
Yes, not sure how you want this to happen through so I didn't do anything yet.

**Comment by peterhaneve** [comment]
Going to take this now and test to see if we have issues with errors.

**Pull request merged**
