### PR TITLE
Updates to fix changed value for reactions (for tracking reaction jobs)

### PR DESCRIPTION
**Pull request by OperatorOverload**
Since early July, it appears that the value returned by ESI for reaction jobs has changed, causing the reaction job counter to be incorrect in the UI.  I've added a new enumeration to the group and called it SimpleReaction, it's not clear why the change was made (I've not found any documentation on it and initially guessed it to be in error), but the SDE appears to still have the old value as well still last I checked.  In any case, this corrects the UI.  I suppose if we think this is a long term change we can change the original value, but this change makes it work either way.

### CODE REVIEW

**Comment by peterhaneve** [comment]
I could not find any references in CCP documentation to this change. What is the difference?

**Comment by OperatorOverload** [comment]
I mentioned in my comment, but I can't find any documentation on the change either.  SDE has not changed (ramActivities) and I haven't seen any other documentation.

However, if you take a look at the values currently coming back from ESI, Reactions used to all be an activity type "11" which lined up with the value in SDE.  Now, Reactions are coming back with an activity type of 9, a value that is not defined in the SDE.

The net result of that is that the job counter is incorrect and always reads that you have the max number of jobs.  I've attached two screenshots, one from the current version built from master in your Repo, and another after the change reflecting the Reaction Jobs Remaining counter with the correct value.  It's easy enough to test for yourself, just start a reaction job and you'll see it.

CurrentVersion

PRFixedVersion

**Comment by peterhaneve** [comment]
If ESI simply returns a different value this change is not too bad, I was curious if there was any case where the old value was also used.

**Comment by OperatorOverload** [comment]
I haven't found one, but since the change wasn't documented I didn't want to just replace the old value, as it's entirely possible it was unintentional and will be reverted at some point.

**Comment by peterhaneve** [comment]
Even the latest SDE has no mention of this change, so I will add it since CCP's ESI team seems to have gone radio silent.

**Pull request merged**
