### PR TITLE
Fix for Issue #82.

### PR DESCRIPTION
**Pull request by avianrr**
This is a fix that should prevent Issue #82 from occurring.

### CODE REVIEW

**Comment by peterhaneve** [comment]
This PR does not get to the real root cause of #82. The TryImport method is responsible for merging completed jobs, but is not finding the parents of the new jobs (possibly because they were retired already) and is thus creating a second entry that gets notified again.

**Comment by avianrr** [comment]
Are you talking about IndustryJob.TryImport?  The only thing that does is update the job information for that object.  It doesn't check for other instances of the job in the collection.  And IndustryJobCollection.Import did not care about jobIDs either.

**Comment by wbSD** [comment]
As far as I can see, the increasing is caused by this flow:

Industry job completed notifications use the Merge behavior
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Collections/Global/GlobalNotificationCollection.cs#L1337

This causes it to merge the new notification with the old (using the notifications own Append method)
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Collections/Global/GlobalNotificationCollection.cs#L69

The industry jobs Append method literally just merges the two lists of completed jobs, which is what causes a single completed job to count as +1 every time the notification completes
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Notifications/IndustryJobsNotificationEventArgs.cs#L51

I think the easy fix here would be that IndustryJobsNotificationEventArgs.Append only appends jobs if they aren't in the Jobs collection already, by comparing the ID of the job being added to the ones already in the list.

**Comment by avianrr** [comment]
Yes but.
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Collections/Global/GlobalNotificationCollection.cs#L1332
Is called from
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Models/CCPCharacter.cs#L892
In the function
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Models/CCPCharacter.cs#L882
Which is attached to an event
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Models/CCPCharacter.cs#L95
Invoked in the function
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/EveMonClient.Events.cs#L841-L848
Which is called from.... Ta-Da...
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Models/Collections/IndustryJobCollection.cs#L162-L164
There very collection I modified to be a Dictionary instead of a list that.... And get this... Now prevents duplicated entries.

Sorry if I seam a little passive-aggressive on that last part, I'm having a bad day!

**Comment by wbSD** [comment]
Sorry to hear about the bad day. Hope you have a better one tomorrow!

I'm not trying to start an argument or anything, I'm just pointing out where I see a problem when I'm trying to reproduce this issue.

I am able to get the industry jobs completed notification to count wrong by simply having a single completed job in industry.
For some reason, when EVEMon does this query, the UpdateOnTimerTick method in IndustryJobCollection runs for two ticks in a row with the same single job in the jobsCompleted list.
Both times that the OnCharacterIndustryJobsCompleted method is called, there is only 1 job in the list, so it's not because the job is in there twice for some reason.
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Models/Collections/IndustryJobCollection.cs#L162-L164

What happens from there is described in my previous comment - the second notification is merged into the first one, and the UpdateDescription causes the description to show 2 completed jobs instead of 1.
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Notifications/IndustryJobsNotificationEventArgs.cs#L62


I'm going to be testing it a bit more now by modifying my industry job list by adding/completing jobs, and see what happens then.

**Comment by wbSD** [comment]
@peterhaneve @avianrr I think I found the exact cause of the problem.
Have a look at the parenthesis of this if:
https://github.com/peterhaneve/evemon/blob/151604d70dd19f9c77a9b87ac685bd762cfaa4eb/src/EVEMon.Common/Models/Collections/IndustryJobCollection.cs#L87-L91
If `limit >= now` it will evaluate as true, and won't ever run the `TryImport` method.

Compare that to how the code looked before the ESI rewrite:
https://github.com/peterhaneve/evemon/blame/9db4f30aceff8745d5ee0c30178b34f182fec452/src/EVEMon.Common/Models/Collections/IndustryJobCollection.cs#L100-L104
Here the `TryImport` is in a separate `.Where` lambda expression, which means it used to also be checked for jobs where `limit >= now`

It was changed in this commit https://github.com/peterhaneve/evemon/commit/3515b8cb1461a1df140a2f4c717d8250bc247440#diff-69bc44291a5539af2108838029713a12R86

I've made a PR which fixes it here https://github.com/peterhaneve/evemon/pull/95

**Comment by avianrr** [comment]
Interesting, my fix moves the TryImport from the if entirely.
https://github.com/avianrr/evemon/blob/IndustryJobFix/src/EVEMon.Common/Models/Collections/IndustryJobCollection.cs#L106-L120
And has the added benefit of not having Items.any call TryImport on the entire collection for every job that's added.

**Comment by wbSD** [comment]
Not gonna argue, dictionary lookup is faster than looping the list with .Any
Just highlighting the reason why your changes fix the problem.
In the end it's up to peterhan what changes will be done to the code.

**Pull request closed without merging**
