### PR TITLE
Rewrite blueprints xml generator

### LINKED ISSUE #114: Blueprints missing from industry
Hi,

Small issue I think: The **Standup Cap Battery I Blueprint** does not show up under industry. The count is adjusted (incorrectly for it) as well. So it looks like i have 1 unused job where I have the max running.

I've seen this in the past as well with new items like the **Assault Damage Control**.

### PR DESCRIPTION
**Pull request by wbSD**
Okay so, this will also fix #114 
This time there are no fudge queries, everything has been rewritten to use the tables available in the sqlite dump

This has the same caveats as #116 regarding market groups, hardcoded blueprint ids and so on.

I've compared the output from this to the one on #116, and it's an almost perfect match! So the other approach did work as well.
There was a difference in the xml attribute for all probability attributes because I had changed the data type to decimal (as it is in the sqlite database). Once I did the same change on #116 they all went away.
After that the only differences left are on the required skills of certain blueprint activities.
These blueprints have duplicate entries in their required skills: 20344, 20352, 20354, 27022
You can verify it by downloading the SDE from developers.eveonline.com and find them in blueprints.yaml - one of them even has the same skill + level 3 times instead of just 2.

This rewritten version does not include those duplicates in the xml file due to some changes I did to RelationSetCollection. The way it used bit-shifting to generate a key for the internal dictionary didn't work well with the new composite keys that were now being put into it (there were some key clashes), so I rewrote it.
When loading the skill requirements from the database, those duplicates are eliminated because they have the same key in the dictionary.

There is a debugging output that checks if all of the expected blueprints were generated. But there are blueprints in blueprints.yaml from the SDE that have a typeID which doesn't exist in typeIDs.yaml (CCP?!), so I've added a check for that in there as well.

### CODE REVIEW

**Comment by peterhaneve** [comment]
I noticed the duplicate entry in the SDE too, I had to add a workaround in the EFT file generator for dictionaries already containing the same key...

The bit shift approach in `RelationSetCollection` only is guaranteed to work for 8-bit keys (0 to 255) despite the use of `long` as the argument type. While the new approach does fix the problem, we need to verify carefully that this does not cause side effects elsewhere.

I doubt that the small perf hit of using an object key will make any real difference, but can we make `Relation` an NNVT (`struct`)? It is never null, immutable, private, consists only of primitive types, is small, never cast or boxed, and rarely assigned/copied.

**Comment by wbSD** [comment]
The RelationSetCollection class is only used within the XmlGenerator project, and apart from the uses that I've added it's only on DgmTypeAttributes, DgmTypeEffects and InvMetaTypes
The number of rows in the RelationSetCollections for those classes have the same number of items as in the sqlite database tables, so it does not seem to cause any problems.

I've changed Relation to struct

**Comment by wbSD** [comment]
I'm pretty sure something can be done to optimize the speed at which some of these files are generated.
The geography datafile iterates through all combinations of mapSolarSystems and invItems, which seems to be the main reason that one is taking so long.

**Comment by wbSD** [comment]
Got the geography file down from 2 minutes 12 seconds to 3 seconds !
For comparison, before it would do 4,405,938,145 iterations to get the planets (8,285 solar systems, 531,797 invItems), now it does 67,961 (the total number of planets).

According to git there are no changes to the geography data file from this

**Comment by peterhaneve** [comment]
I did not believe that `InvTypesTable[]` actually iterated everything there, is it not constant time? That would explain why caching the planets took so long (but it saved tons of ESI calls in the client so it felt like a win either way).

**Comment by wbSD** [comment]
It's not the InvTypesTable lookup that eats up the iterations, but the InvItemsTable.
For each solarsystem it runs `InvItemsTable.Where(stuff)` which means that every item in there has to be evaluated for `stuff` for each solar system.

**Comment by wbSD** [comment]
I managed to also optimize the generation of the items datafile.
It is now down from almost 3 minutes to 7 seconds
Git says the gzip file is the same between the old and new code, and running a compare on the old/new xml files also says they match

The slow ones are now:
Blueprints: 17 seconds
Reprocessing: 17 seconds
I think the amount of time saved compared to how much it takes to optimize it isn't worth it any more

**Comment by peterhaneve** [comment]
I was working on some similar changes, so I will take this for now and merge it on my side.

**Pull request merged**
