### PR TITLE
ETag null ref fix: Only run if result has data

### PR DESCRIPTION
**Pull request by wbSD**
This is easy to reproduce, just make the server status query monitor run again.

### CODE REVIEW

**Comment by stcarlso** [comment]
The intent is to leave the result null and check HasData. In the case of large result sets, this would prevent the code re-importing the data again and would allow the set to be GCed.

I believe that I went through all references and checked for null refs, did we miss one? I turned in literally everything in a test run and did not get any exceptions.

**Comment by wbSD** [comment]
The null ref only happens for server status.
The difference seems to be that all character, corporation and ESI key query monitors are new classes that inherit from the base QueryMonitor class, and they all have their own custom callback that only invokes the onSuccess callback if result.HasData is true.
But the server status query montitor is just the base class, so it doesn't have this check.
https://github.com/peterhaneve/evemon/blob/master/src/EVEMon.Common/Models/EveServer.cs#L28
I've adjusted the pull request to add that check to QueryMonitor.

I should also point out that there might be a problem with the LastResult.Result not keeping the old value.
Some code was added to the skill import where it re-uses the last skill queue result. It does that because ESI doesn't give you up to date data from Skills, if any of the skills in the queue are completed. They will still be listed as their original level until you actually log into EVE.
https://github.com/peterhaneve/evemon/blob/master/src/EVEMon.Common/QueryMonitor/CharacterDataQuerying.cs#L400

**Comment by peterhaneve** [comment]
CharacterDataQuerying.cs#L400 does not execute if a "Not Modified" result is reported. How would this cause a skill queue issue? It would be equivalent to having a skill complete while the query monitor is on cooldown due to refresh interval, which is handled correctly already.

**Comment by wbSD** [comment]
It requires a bit of bad luck combinations, but if you end up with callback for Skill Queue -> Skill Queue -> Skills, the skills import will revert the skill levels that are completed in the queue.

It's not really related to the null ref of this pull request though, and I guess not very likely to happen.
I just brought it up because it's code that I wrote and I know that it uses LastResult.Result.

**Comment by peterhaneve** [comment]
I looked at it and I think I understand the potential failure mode here. Therefore, I took the compromise route of not importing or notifying (the big perf drains) on a 304, but keeping the previous result's data if a 304 is returned for that case. Investigating memory usage showed that keeping the ESI results around only makes a noticeable impact in niche cases, and it will be no worse than it is now (no reports yet of out of memory issues even from people with 50 characters)

**Pull request closed without merging**
