### PR TITLE
Dynamically add missing notifications

### PR DESCRIPTION
**Pull request by wvdvegt**
Added code to dynamically add missing EveNotificationType items. This way the Notification tabs does not show 'Unknow' as subject anymore.

### CODE REVIEW

**Comment by wvdvegt** [comment]
Please only look at commit da0ea29 (I still get annoyed by this forking as it pulled in again all other changes too). 
Looking forward to the next release!

**Comment by wvdvegt** [comment]
The patches eddae7d and 6d17d93 belong together. 

- The first one (eddae7d) removes empty kill log files, the 2nd one correctly de-serializes the remaining kill log files. This patch needs one start of Evemon to remove the empty kill logs. After that the remaining exceptions are caused by non-empty kill logs.
- Although not tested, the 2nd patch (6d17d93) alone might cure the empty kill log issue as well. It also corrects the attributes on the de-serialized class.

**Comment by wbSD** [comment]
@wvdvegt you need to get your master branch reset, and then every time you want to make a change you sync your master branch with peterhan's master, and then create a new branch to do your changes on.
If you keep making separate branches for each change, they won't end up in one big pile like here.
The tricky part(s) are to reset your master branch, figure out how to sync it with his master, and maybe the whole branching thing if you don't have experience with it.

**Comment by wvdvegt** [comment]
Please only merge commit 89a3ba9 as it's the same as da0ea29 but after resyncing/merging with the upstream repo.

**Comment by peterhaneve** [comment]
I noticed that the template file is still at bitbucket, so as a workaround the current EVEMon code never uses it and prefers its local version instead.

Preferably, we would be able to get an updated version of this file with all of the appropriate text. I searched the SDE high and low but came up empty. Do you know where an updated version might be?

**Comment by wvdvegt** [comment]
I don't think there is a template. CCP mentioned it a bit of a minefield on #esi slack.

In a private tool I'm building (an UWP app) I managed to encode 50 or so notification almost 1:1 based on what I received. What I do not have in my inbox I can't decode (like null sec sov stuff) . Some of those cannot be done with the templating method.

**Comment by wvdvegt** [comment]
No problem with sharing but i need some time to clean the code a bit from example in/output. 
Btw is there any way we can share this privately?

**Comment by peterhaneve** [comment]
There still was some fallout in the commit history after this merge, but it looks manageable.

**Comment by wvdvegt** [comment]
Great, it's a quick fix to make the notifications more readable (remove the 'unknown') until all notifications are properly decoded. Need to check if all helper code is included.

I'll send you a link with my notification decoding code in the upcoming days. I managed to decode 57 of them so far.

Method is quite simple, I convert the content of text (which is yaml) into json (using Json.NET) and use [SimpleJSON](https://github.com/Bunny83/SimpleJSON) to access it without the need of models. Json.NET can also do it but I found SimpleJSON more flexible and lightweight.

**Comment by peterhaneve** [comment]
Thanks for the update with your decoding. However, I noticed that some fields still have hard coded values in your source - check carefully for references to your corp and for fixed date/times.

**Pull request merged**
