### PR TITLE
Fix skillpoint calculation, Max->Min

### PR DESCRIPTION
**Pull request by SamuelHusky**
Resolves skill SP calculation issue described in Pull #12

### CODE REVIEW

**Comment by SamuelHusky** [comment]
It's actually not even started training, but it's planned up to 3 which is where it's getting it's 7072 from as that will be the SP displayed normally on the level 3 training, after making the change I made my skill queue now looks like this.

image

image

Which is what I would expect, whereas before it was showing as 7072 for every level of the skill which resulted in negative figures for level 1, no training time for level 2 and a correct training time for level 3

**Comment by wbSD** [comment]
Hmm... So the character skill points is being bumped up even though it isn't completed.
Maybe the else should be changed to check that the skill is currently training
`else if (queuedSkill.IsTraining)`
At the skill import time, the skill queue should be up to date, as it is updated on import.

**Comment by SamuelHusky** [comment]
Yeah it's certainly odd, let me try out the else if in my branch, if that works too I'll update this pull while it's still open

**Comment by SamuelHusky** [comment]
Actually thinking about it, I'm not sure that would work either. I certainly would resolve the problems with the Drone skill, however my current training skill is Assault Frigates 4, if I had 5 in the queue with the else if and the Max, the level 4 would always show the StartSP of the level 5 skill. The dictionary would then have the skill Assault Frigates 5 only and then the Max would evaluate wrong

**Comment by wbSD** [comment]
I looked at the code again, this time trying not to use QueuedSkill and only use the data from ESI to determine if the skills in the queue are completed or currently training.

I was able to reproduce the bug that you described here, and these changes solved it.
@SamuelHusky Could I ask you to give it a swing and see if you agree?
https://github.com/wbSD/evemon/compare/master...wbSD:MoreSkillIssues

**Comment by wbSD** [comment]
I'll do one from my branch, that's probably easier.

**Comment by SamuelHusky** [comment]
Roger, thanks for coming up with a better fix, closing this pull.

**Pull request closed without merging**
